toc:
    -
        name: core
        file: src/core/readme.md
    - CoreTypes
    - Decoder
    - Filter
    - Image2D
    - Image3D
    - Image3DAlt
    - ImageToImageFilter
    - LineString
    - Mesh3D
    - MniVolume
    - PixpipeContainer
    - PixpipeContainerMultiData
    - PixpipeObject
    - Signal1D
    -
        name: decoder
        file: src/decoder/readme.md
    - AllFormatsGenericDecoder
    - EdfDecoder
    - EegModDecoder
    - GenericDecoderInterface
    - Image2DGenericDecoder
    - Image3DGenericDecoder
    - Image3DGenericDecoderAlt
    - JSONDecoder
    - JpegDecoder
    - Mesh3DGenericDecoder
    - MghDecoder
    - MghDecoderAlt
    - Minc2Decoder
    - Minc2DecoderAlt
    - MniObjDecoder
    - NiftiDecoder
    - NiftiDecoderAlt
    - PixBinDecoder
    - PixBinEncoder
    - PixpDecoder
    - PixpEncoder
    - PngDecoder
    - Signal1DGenericDecoder
    - TiffDecoder
    -
        name: filter
    - ApplyColormapFilter
    - BandPassSignal1D
    - ComponentMergeImage2DFilter
    - ComponentProjectionImage2DFilter
    - ContourHolesImage2DFilter
    - ContourImage2DFilter
    - CropImageFilter
    - DifferenceEquationSignal1D
    - FloodFillImageFilter
    - ForEachPixelImageFilter
    - ForEachPixelReadOnlyFilter
    - FourierImageFilters
    - FourierSignalFilters
    - GradientImageFilter
    - HighPassSignal1D
    - IDWSparseInterpolationImageFilter
    - Image3DToMosaicFilter
    - Image3DToMosaicFilterAlt
    - ImageBlendExpressionFilter
    - ImageDerivativeFilter
    - LowPassFreqSignal1D
    - LowPassSignal1D
    - Mesh3DToVolumetricHullFilter
    - MultiplyImageFilter
    - NaturalNeighborSparseInterpolationImageFilter
    - NearestNeighborSparseInterpolationImageFilter
    - NormalizeImageFilter
    - PatchImageFilter
    - SimpleThresholdFilter
    - SimplifyLineStringFilter
    - SpatialConvolutionFilter
    - SpectralScaleImageFilter
    - TerrainRgbToElevationImageFilter
    - TriangulationSparseInterpolationImageFilter
    -
        name: helper
    - AngleToHueWheelHelper
    - ColorScales
    - Colormap
    - LineStringPrinterOnImage2DHelper
    -
        name: io
    - BrowserDownloadBuffer
    - CanvasImageWriter
    - FileImageReader
    - FileToArrayBufferReader
    - UrlImageReader
    - UrlToArrayBufferReader
    -
        name: utils
    - FunctionGenerator
    - Image3DMetadataConverter
    - MatrixTricks
